<a href="https://colab.research.google.com/github/Asrorbek2605/data_preparation/blob/main/data_preparation_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv",index_col = "country")
df.head()

           rank     density   densityMi   pop2021  area
country
Macau         1  21946.4667  56841.3487   658.394    30
Monaco        2  19755.5000  51166.7450    39.511     2
Singapore     3   8305.1915  21510.4461  5896.686   710
Hong Kong     4   6841.3134  17719.0017  7552.810  1104
Gibraltar     5   5616.3333  14546.3033    33.698     6

In [ ]:
df.loc['Uzbekistan']

rank            133.0000
density          75.8511
densityMi       196.4542
pop2021       33935.7630
area         447400.0000
Name: Uzbekistan, dtype: float64

In [ ]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [ ]:
population = df.pop2021

In [ ]:
band = pd.cut(population,bins)
band

country
Macau                   (0, 1000]
Monaco                  (0, 1000]
Singapore           (1000, 10000]
Hong Kong           (1000, 10000]
Gibraltar               (0, 1000]
                        ...
Namibia             (1000, 10000]
Western Sahara          (0, 1000]
Mongolia            (1000, 10000]
Falkland Islands        (0, 1000]
Greenland               (0, 1000]
Name: pop2021, Length: 232, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [ ]:
band.value_counts()

(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: pop2021, dtype: int64

In [ ]:
df['band'] = band
df.head()

           rank     density   densityMi   pop2021  area           band
country
Macau         1  21946.4667  56841.3487   658.394    30      (0, 1000]
Monaco        2  19755.5000  51166.7450    39.511     2      (0, 1000]
Singapore     3   8305.1915  21510.4461  5896.686   710  (1000, 10000]
Hong Kong     4   6841.3134  17719.0017  7552.810  1104  (1000, 10000]
Gibraltar     5   5616.3333  14546.3033    33.698     6      (0, 1000]

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv",index_col = 0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.price.describe() #bizga malumot chiqarib beradi

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [ ]:
bins  = [0,10000,20000,50000]

In [ ]:
range = pd.cut(df.price,bins)
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [ ]:
range.value_counts()

(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: price, dtype: int64

In [ ]:
names =   ["arzon","orta","qimmat"]
range = pd.cut(df.price,bins,labels=names)
range.value_counts()

arzon     28
orta      17
qimmat    13
Name: price, dtype: int64

In [ ]:
range = pd.cut(df.price,3)
range.value_counts()

(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: price, dtype: int64

In [ ]:
range = pd.qcut(df.horsepower,3)
range.value_counts()

(47.999, 70.0]    24
(111.0, 288.0]    20
(70.0, 111.0]     17
Name: horsepower, dtype: int64

**Groupby yordamida guruhlash**

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv",index_col = 0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.company.value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

In [ ]:
df.groupby('company').mean()

<ipython-input-23-68a802e890b6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('company').mean()

,wheel-base,length,horsepower,average-mileage,price
company,,,,,
alfa-romero,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,104.300000,188.800000,114.000000,23.000000,13177.500000

In [ ]:
df.groupby('company').max()

,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
company,,,,,,,,
alfa-romero,hatchback,94.5,171.2,ohcv,six,154,21,16500.0
audi,wagon,105.8,192.7,ohc,four,115,24,18920.0
bmw,sedan,110.0,197.0,ohc,six,182,23,41315.0
chevrolet,sedan,94.5,158.8,ohc,three,70,47,6575.0
dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
honda,wagon,96.5,175.4,ohc,four,101,30,12945.0
isuzu,sedan,94.5,170.7,ohc,four,78,38,6785.0
jaguar,sedan,113.0,199.6,ohcv,twelve,262,15,36000.0
mazda,sedan,104.9,175.0,rotor,two,101,31,18344.0
mercedes-benz,wagon,120.9,208.1,ohcv,five,184,22,45400.0
mitsubishi,sedan,96.3,172.4,ohc,four,88,37,8189.0
nissan,wagon,100.4,184.6,ohcv,six,152,45,13499.0
porsche,hatchback,98.4,175.7,ohcf,six,288,17,37028.0
toyota,wagon,104.5,187.8,ohc,six,156,35,15750.0
volkswagen,sedan,97.3,171.7,ohc,four,100,37,9995.0
volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.groupby(['company','body-style']).price.max()

company        body-style
alfa-romero    convertible    16500.0
               hatchback      16500.0
audi           sedan          17450.0
               wagon          18920.0
bmw            sedan          41315.0
chevrolet      hatchback       6295.0
               sedan           6575.0
dodge          hatchback       6377.0
honda          sedan          12945.0
               wagon           7295.0
isuzu          sedan           6785.0
jaguar         sedan          36000.0
mazda          hatchback      11845.0
               sedan          18344.0
mercedes-benz  hardtop        45400.0
               sedan          40960.0
               wagon          28248.0
mitsubishi     hatchback       6189.0
               sedan           8189.0
nissan         sedan          13499.0
               wagon           7349.0
porsche        convertible    37028.0
               hardtop        34028.0
               hatchback          NaN
toyota         hatchback       6488.0
               wagon          15750.0
volkswagen     sedan           9995.0
volvo          sedan          12940.0
               wagon          13415.0
Name: price, dtype: float64

In [ ]:
df.groupby(['company']).agg([max,min,np.mean])

<ipython-input-29-aae3f436ae49>:1: FutureWarning: ['body-style', 'engine-type', 'num-of-cylinders'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby(['company']).agg([max,min,np.mean])

              wheel-base                    length                     \
                     max    min        mean    max    min        mean
company
alfa-romero         94.5   88.6   90.566667  171.2  168.8  169.600000
audi               105.8   99.4  101.200000  192.7  176.6  180.800000
bmw                110.0  101.2  103.433333  197.0  176.8  185.033333
chevrolet           94.5   88.4   92.466667  158.8  141.1  151.933333
dodge               93.7   93.7   93.700000  157.3  157.3  157.300000
honda               96.5   96.5   96.500000  175.4  157.1  167.200000
isuzu               94.5   94.3   94.433333  170.7  155.9  160.833333
jaguar             113.0  102.0  109.333333  199.6  191.7  196.966667
mazda              104.9   93.1   95.900000  175.0  159.1  164.260000
mercedes-benz      120.9  110.0  113.225000  208.1  190.9  197.275000
mitsubishi          96.3   93.7   95.000000  172.4  157.3  164.850000
nissan             100.4   94.5   95.680000  184.6  165.3  170.140000
porsche             98.4   89.5   92.466667  175.7  168.9  171.166667
toyota             104.5   95.7   96.957143  187.8  158.7  167.571429
volkswagen          97.3   97.3   97.300000  171.7  171.7  171.700000
volvo              104.3  104.3  104.300000  188.8  188.8  188.800000

              horsepower                  average-mileage                 \
                     max  min        mean             max min       mean
company
alfa-romero          154  111  125.333333              21  19  20.333333
audi                 115  102  109.250000              24  18  20.000000
bmw                  182  101  144.833333              23  15  19.000000
chevrolet             70   48   62.666667              47  38  41.000000
dodge                 68   68   68.000000              31  31  31.000000
honda                101   76   92.333333              30  24  26.333333
isuzu                 78   70   72.666667              38  24  33.333333
jaguar               262  176  204.666667              15  13  14.333333
mazda                101   68   75.400000              31  17  28.000000
mercedes-benz        184  123  153.500000              22  14  18.000000
mitsubishi            88   68   78.000000              37  25  29.500000
nissan               152   55   82.800000              45  19  31.400000
porsche              288  207  234.000000              17  17  17.000000
toyota               156   62   75.428571              35  19  28.714286
volkswagen           100   52   72.250000              37  26  31.750000
volvo                114  114  114.000000              23  23  23.000000

                 price
                   max      min          mean
company
alfa-romero    16500.0  13495.0  15498.333333
audi           18920.0  13950.0  16392.500000
bmw            41315.0  16430.0  27213.333333
chevrolet       6575.0   5151.0   6007.000000
dodge           6377.0   6229.0   6303.000000
honda          12945.0   7295.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         36000.0  32250.0  34600.000000
mazda          18344.0   5195.0   9654.800000
mercedes-benz  45400.0  25552.0  35040.000000
mitsubishi      8189.0   5389.0   6689.000000
nissan         13499.0   6649.0   8289.000000
porsche        37028.0  34028.0  35528.000000
toyota         15750.0   5348.0   8216.857143
volkswagen      9995.0   7775.0   8435.000000
volvo          13415.0  12940.0  13177.500000